---
slug: testbook
filename: testbook
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2015
uuid: 944e5f2f-5a1a-4cfb-b1d9-c56ed454d126
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
